"use client"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
import { AppContext } from "./context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [listOfColleges, setListOfColleges] = useState([])


const appSettings = {
  listOfColleges,
  updateListOfColleges: (colleges:any) => {
    setListOfColleges(colleges)
  },
  getColleges:async () => {
    const data = await fetch('http://universities.hipolabs.com/search?country=United%20States&limit=50');
    const schools = await data.json();
    return schools;
  },
  getCookie: (cname:string) => {
    let name = cname + "=";
    let decodedCookie = decodeURIComponent(document.cookie);
    let ca = decodedCookie.split(';');
    for(let i = 0; i <ca.length; i++) {
      let c = ca[i];
      while (c.charAt(0) == ' ') {
        c = c.substring(1);
      }
      if (c.indexOf(name) == 0) {
        return c.substring(name.length, c.length);
      }
    }
    return "";
  }
}

useEffect(() => {
  
  const getColleges = async () => {
    const data = await fetch('http://universities.hipolabs.com/search?country=United%20States&limit=50');
    const schools = await data.json();
    appSettings.updateListOfColleges(schools);
  }
  
  getColleges();
});


  return (
    <AppContext.Provider value={appSettings}>
      <html lang="en">
        <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </AppContext.Provider>
  );
}